---
spring:
  profiles:
    active: "@profile.active@"
  jackson:
   # serialization:
    #  write-dates-as-timestamps: false
    #date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
    port: 8088
mybatis-plus:
 # mapper-locations: classpath*:/mapper/**/*Mapper.xml ## Mapper对应的 XML文件位置
  type-enums-package: com.example.demo.domain.enums
---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flyway_dev?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: yourPassword
    type: com.zaxxer.hikari.HikariDataSource

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    # 连接超时时间 单位 ms（毫秒）
    timeout: 3000
    password: yourPassword
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0

  flyway:
    enabled: true
    locations: classpath:db/migration/dev
    table: flyway_schema_history
    baseline-on-migrate: true
    baseline-version: 1
    placeholders:
      flyway-table: ${spring.flyway.table}

  task:
    scheduling:
      threadNamePrefix: myScheduling-

logging:
  level:
    com:
      example:
        demo:
          mapper: debug

---
spring:
  profiles: qa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flyway_qa?serverTimezone=GMT%2B8
    username: root
    password: yourPassword
    type: com.zaxxer.hikari.HikariDataSource

  flyway:
    enabled: true
    locations: classpath:db/migration/qa
    table: flyway_schema_history
    encoding: UTF-8
    out-of-order: false
    validate-on-migrate: true
    schemas: flyway_qa
